// wallpaper.c — Wallpaper page:
//  - scope chips: All monitors, or one chip per connected monitor
//  - folder row: where wallpapers live (persisted)
//  - thumbnail grid: click to apply to the selected scope via hyprpaper
//    IPC (hyprctl hyprpaper reload), instant, no flicker
//
// Choices persist twice: ~/.config/nekoland/wallpaper.conf (page state)
// and ~/.config/hypr/hyprpaper.conf (hyprpaper >= 0.8 wallpaper blocks),
// so hyprpaper restores everything by itself at login.

#include "app.h"

#include <json-glib/json-glib.h>
#include <string.h>

static GtkWidget *chips_box;    // scope chips
static GtkWidget *folder_label;
static GtkWidget *thumb_flow;
static GtkWidget *status_label;
static GtkWidget *page_root;

static char *wp_folder;
static char *wp_all;        // wildcard wallpaper (all monitors)
static GHashTable *wp_mon;  // monitor name -> per-monitor override path
static GPtrArray *monitors; // char*
static char *sel_monitor;   // NULL = "All monitors"

// ---- persistence ----

static char *wp_state_path(void) {
    return g_build_filename(g_get_user_config_dir(), "nekoland",
                            "wallpaper.conf", NULL);
}

static char *hyprpaper_conf_path(void) {
    return g_build_filename(g_get_user_config_dir(), "hypr",
                            "hyprpaper.conf", NULL);
}

// regenerate hyprpaper.conf: wildcard block + per-monitor overrides
static void hyprpaper_conf_write(void) {
    GString *s = g_string_new(
        "# generated by nekoland-settings (Wallpaper page) — edits here\n"
        "# are overwritten; hyprpaper >= 0.8 wallpaper-block format\n\n");
    if (wp_all)
        g_string_append_printf(s,
                               "wallpaper {\n    monitor =\n    path = %s\n"
                               "    fit_mode = cover\n}\n\n",
                               wp_all);
    GHashTableIter it;
    gpointer k, v;
    g_hash_table_iter_init(&it, wp_mon);
    while (g_hash_table_iter_next(&it, &k, &v))
        g_string_append_printf(s,
                               "wallpaper {\n    monitor = %s\n"
                               "    path = %s\n    fit_mode = cover\n}\n\n",
                               (char *)k, (char *)v);
    g_string_append(s, "splash = false\n");
    char *path = hyprpaper_conf_path();
    g_file_set_contents(path, s->str, -1, NULL);
    g_free(path);
    g_string_free(s, TRUE);
}

static void wp_state_save(void) {
    GKeyFile *kf = g_key_file_new();
    if (wp_folder)
        g_key_file_set_string(kf, "wallpaper", "folder", wp_folder);
    if (wp_all)
        g_key_file_set_string(kf, "wallpaper", "all", wp_all);
    GHashTableIter it;
    gpointer k, v;
    g_hash_table_iter_init(&it, wp_mon);
    while (g_hash_table_iter_next(&it, &k, &v))
        g_key_file_set_string(kf, "monitors", k, v);
    char *path = wp_state_path();
    char *dir = g_path_get_dirname(path);
    g_mkdir_with_parents(dir, 0755);
    g_key_file_save_to_file(kf, path, NULL);
    g_free(dir);
    g_free(path);
    g_key_file_free(kf);
    hyprpaper_conf_write();
}

// first run: adopt the wallpaper already named in hyprpaper.conf
static char *hyprpaper_conf_first_path(void) {
    char *path = hyprpaper_conf_path();
    char *text = NULL;
    char *found = NULL;
    if (g_file_get_contents(path, &text, NULL, NULL)) {
        for (char **l = g_strsplit(text, "\n", -1), **p = l; *p; p++) {
            char *line = g_strstrip(*p);
            if (g_str_has_prefix(line, "path")) {
                char *eq = strchr(line, '=');
                if (eq) {
                    found = g_strdup(g_strstrip(eq + 1));
                    break;
                }
            }
        }
        g_free(text);
    }
    g_free(path);
    return found;
}

static void wp_state_load(void) {
    wp_mon = g_hash_table_new_full(g_str_hash, g_str_equal, g_free, g_free);
    GKeyFile *kf = g_key_file_new();
    char *path = wp_state_path();
    if (g_key_file_load_from_file(kf, path, G_KEY_FILE_NONE, NULL)) {
        wp_folder = g_key_file_get_string(kf, "wallpaper", "folder", NULL);
        wp_all = g_key_file_get_string(kf, "wallpaper", "all", NULL);
        gsize n = 0;
        char **keys = g_key_file_get_keys(kf, "monitors", &n, NULL);
        for (gsize i = 0; keys && i < n; i++) {
            char *v = g_key_file_get_string(kf, "monitors", keys[i], NULL);
            if (v)
                g_hash_table_insert(wp_mon, g_strdup(keys[i]), v);
        }
        g_strfreev(keys);
    }
    g_free(path);
    g_key_file_free(kf);

    if (!wp_folder) {
        char *cand = g_build_filename(g_get_home_dir(), "Pictures",
                                      "Wallpapers", NULL);
        if (g_file_test(cand, G_FILE_TEST_IS_DIR)) {
            wp_folder = cand;
        } else {
            g_free(cand);
            const char *pics =
                g_get_user_special_dir(G_USER_DIRECTORY_PICTURES);
            wp_folder = g_strdup(pics ? pics : g_get_home_dir());
        }
    }
    if (!wp_all)
        wp_all = hyprpaper_conf_first_path();
}

// ---- applying ----

static void hyprpaper_apply(const char *mon, const char *path) {
    // hyprpaper >= 0.8 IPC: only "wallpaper mon,path" exists — it
    // auto-preloads and swaps live; empty monitor = all monitors
    // (preload/unload/reload were removed with the 0.8 rewrite)
    char *arg = g_strdup_printf("%s,%s", mon ? mon : "", path);
    const char *argv[] = {"hyprctl", "hyprpaper", "wallpaper", arg, NULL};
    g_spawn_async(NULL, (char **)argv, NULL, G_SPAWN_SEARCH_PATH, NULL,
                  NULL, NULL, NULL);
    g_free(arg);
}

// the wallpaper currently effective for the selected scope
static const char *scope_current(void) {
    if (sel_monitor) {
        const char *o = g_hash_table_lookup(wp_mon, sel_monitor);
        return o ? o : wp_all;
    }
    return wp_all;
}

static void mark_selection(void) {
    const char *cur = scope_current();
    for (GtkWidget *c = gtk_widget_get_first_child(thumb_flow); c;
         c = gtk_widget_get_next_sibling(c)) {
        GtkWidget *btn = gtk_flow_box_child_get_child(GTK_FLOW_BOX_CHILD(c));
        const char *p = g_object_get_data(G_OBJECT(btn), "wp-path");
        if (cur && p && g_str_equal(cur, p))
            gtk_widget_add_css_class(btn, "sel");
        else
            gtk_widget_remove_css_class(btn, "sel");
    }
}

static void on_thumb_clicked(GtkWidget *btn, gpointer data) {
    (void)data;
    const char *path = g_object_get_data(G_OBJECT(btn), "wp-path");
    if (!path)
        return;
    if (sel_monitor) {
        g_hash_table_insert(wp_mon, g_strdup(sel_monitor), g_strdup(path));
    } else {
        g_free(wp_all);
        wp_all = g_strdup(path);
        // "All" is an explicit reset: per-monitor overrides go away
        g_hash_table_remove_all(wp_mon);
    }
    hyprpaper_apply(sel_monitor, path);
    wp_state_save();
    mark_selection();
    char *base = g_path_get_basename(path);
    char *msg = g_strdup_printf("%s → %s", base,
                                sel_monitor ? sel_monitor : "all monitors");
    gtk_label_set_text(GTK_LABEL(status_label), msg);
    g_free(msg);
    g_free(base);
}

// ---- scope chips ----

static void rebuild_chips(void);

static void str_notify(gpointer data, GClosure *closure) {
    (void)closure;
    g_free(data);
}

static void on_chip_clicked(GtkWidget *btn, gpointer data) {
    (void)btn;
    g_free(sel_monitor);
    sel_monitor = data ? g_strdup(data) : NULL;
    rebuild_chips();
    mark_selection();
}

static void chips_clear(void) {
    GtkWidget *c;
    while ((c = gtk_widget_get_first_child(chips_box)))
        gtk_box_remove(GTK_BOX(chips_box), c);
}

static GtkWidget *chip_new(const char *title, const char *sub,
                           gboolean selected, const char *mon) {
    GtkWidget *chip = gtk_button_new();
    gtk_widget_add_css_class(chip, "dev-chip");
    if (selected)
        gtk_widget_add_css_class(chip, "sel");
    GtkWidget *v = gtk_box_new(GTK_ORIENTATION_VERTICAL, 2);
    GtkWidget *t = gtk_label_new(title);
    gtk_widget_add_css_class(t, "chip-title");
    gtk_label_set_xalign(GTK_LABEL(t), 0.0);
    gtk_box_append(GTK_BOX(v), t);
    if (sub) {
        GtkWidget *s = gtk_label_new(sub);
        gtk_widget_add_css_class(s, "chip-sub");
        gtk_label_set_xalign(GTK_LABEL(s), 0.0);
        gtk_box_append(GTK_BOX(v), s);
    }
    gtk_button_set_child(GTK_BUTTON(chip), v);
    if (mon)
        g_signal_connect_data(chip, "clicked", G_CALLBACK(on_chip_clicked),
                              g_strdup(mon), str_notify, 0);
    else
        g_signal_connect(chip, "clicked", G_CALLBACK(on_chip_clicked),
                         NULL);
    return chip;
}

static void rebuild_chips(void) {
    chips_clear();
    gtk_box_append(GTK_BOX(chips_box),
                   chip_new("All monitors", "one wallpaper everywhere",
                            sel_monitor == NULL, NULL));
    for (guint i = 0; monitors && i < monitors->len; i++) {
        const char *m = g_ptr_array_index(monitors, i);
        const char *sub = g_hash_table_lookup(wp_mon, m) ? "custom"
                                                         : "follows All";
        gtk_box_append(
            GTK_BOX(chips_box),
            chip_new(m, sub, sel_monitor && g_str_equal(sel_monitor, m), m));
    }
}

static void monitors_load(void) {
    if (monitors)
        g_ptr_array_free(monitors, TRUE);
    monitors = g_ptr_array_new_with_free_func(g_free);
    char *out = NULL;
    if (!g_spawn_command_line_sync("hyprctl monitors -j", &out, NULL, NULL,
                                   NULL))
        return;
    JsonParser *p = json_parser_new();
    if (out && json_parser_load_from_data(p, out, -1, NULL)) {
        JsonArray *arr = json_node_get_array(json_parser_get_root(p));
        for (guint i = 0; i < json_array_get_length(arr); i++) {
            JsonObject *o = json_array_get_object_element(arr, i);
            const char *name = json_object_get_string_member(o, "name");
            if (name)
                g_ptr_array_add(monitors, g_strdup(name));
        }
    }
    g_object_unref(p);
    g_free(out);
}

// ---- thumbnails ----

typedef struct {
    char *path;
    GdkPixbuf *pix;
} Thumb;

static void thumb_free(gpointer p) {
    Thumb *t = p;
    g_free(t->path);
    g_clear_object(&t->pix);
    g_free(t);
}

static gboolean is_image_name(const char *name) {
    static const char *ext[] = {".jpg", ".jpeg", ".png", ".webp",
                                ".bmp", ".gif",  NULL};
    for (int i = 0; ext[i]; i++)
        if (g_str_has_suffix(name, ext[i]))
            return TRUE;
    return FALSE;
}

static gint thumb_cmp(gconstpointer a, gconstpointer b) {
    const Thumb *ta = *(Thumb *const *)a, *tb = *(Thumb *const *)b;
    return g_ascii_strcasecmp(ta->path, tb->path);
}

static void thumbs_thread(GTask *task, gpointer src, gpointer data,
                          GCancellable *cancel) {
    (void)src;
    (void)cancel;
    char *folder = data;
    GPtrArray *thumbs = g_ptr_array_new_with_free_func(thumb_free);
    GDir *dir = g_dir_open(folder, 0, NULL);
    const char *name;
    while (dir && (name = g_dir_read_name(dir))) {
        char *low = g_ascii_strdown(name, -1);
        gboolean img = is_image_name(low);
        g_free(low);
        if (!img)
            continue;
        char *full = g_build_filename(folder, name, NULL);
        GdkPixbuf *pix =
            gdk_pixbuf_new_from_file_at_scale(full, 480, 480, TRUE, NULL);
        if (pix) {
            // centre-crop to exactly 16:9, then scale to the tile size,
            // so every tile pixbuf is 208×117 regardless of source shape
            int w = gdk_pixbuf_get_width(pix);
            int h = gdk_pixbuf_get_height(pix);
            int cw = w, ch = w * 9 / 16;
            if (ch > h) {
                ch = h;
                cw = MIN(w, h * 16 / 9);
            }
            GdkPixbuf *crop = gdk_pixbuf_new_subpixbuf(
                pix, (w - cw) / 2, (h - ch) / 2, cw, ch);
            GdkPixbuf *tile = gdk_pixbuf_scale_simple(crop, 208, 117,
                                                      GDK_INTERP_BILINEAR);
            g_object_unref(crop);
            g_object_unref(pix);
            Thumb *t = g_new0(Thumb, 1);
            t->path = full;
            t->pix = tile;
            g_ptr_array_add(thumbs, t);
        } else {
            g_free(full);
        }
    }
    if (dir)
        g_dir_close(dir);
    g_ptr_array_sort(thumbs, thumb_cmp);
    g_task_return_pointer(task, thumbs,
                          (GDestroyNotify)g_ptr_array_unref);
}

static void flow_clear(void) {
    GtkWidget *c;
    while ((c = gtk_widget_get_first_child(thumb_flow)))
        gtk_flow_box_remove(GTK_FLOW_BOX(thumb_flow), c);
}

static void thumbs_done(GObject *src, GAsyncResult *res, gpointer data) {
    (void)src;
    (void)data;
    GPtrArray *thumbs = g_task_propagate_pointer(G_TASK(res), NULL);
    flow_clear();
    if (!thumbs || thumbs->len == 0) {
        gtk_label_set_text(GTK_LABEL(status_label),
                           "no images in this folder");
        if (thumbs)
            g_ptr_array_unref(thumbs);
        return;
    }
    for (guint i = 0; i < thumbs->len; i++) {
        Thumb *t = g_ptr_array_index(thumbs, i);
        GtkWidget *btn = gtk_button_new();
        gtk_widget_add_css_class(btn, "wp-thumb");
        GdkTexture *tex = gdk_texture_new_for_pixbuf(t->pix);
        GtkWidget *pic = gtk_picture_new_for_paintable(GDK_PAINTABLE(tex));
        g_object_unref(tex);
        // pixbufs are pre-cropped to a uniform 208×117 — show them 1:1
        gtk_picture_set_can_shrink(GTK_PICTURE(pic), FALSE);
        gtk_widget_set_valign(btn, GTK_ALIGN_START);
        gtk_widget_set_halign(btn, GTK_ALIGN_START);
        gtk_widget_add_css_class(pic, "wp-pic");
        gtk_button_set_child(GTK_BUTTON(btn), pic);
        char *base = g_path_get_basename(t->path);
        gtk_widget_set_tooltip_text(btn, base);
        g_free(base);
        g_object_set_data_full(G_OBJECT(btn), "wp-path",
                               g_strdup(t->path), g_free);
        g_signal_connect(btn, "clicked", G_CALLBACK(on_thumb_clicked),
                         NULL);
        gtk_flow_box_append(GTK_FLOW_BOX(thumb_flow), btn);
    }
    char buf[64];
    g_snprintf(buf, sizeof(buf), "%u wallpapers", thumbs->len);
    gtk_label_set_text(GTK_LABEL(status_label), buf);
    g_ptr_array_unref(thumbs);
    mark_selection();
}

static void thumbs_scan(void) {
    gtk_label_set_text(GTK_LABEL(status_label), "loading…");
    GTask *task = g_task_new(NULL, NULL, thumbs_done, NULL);
    g_task_set_task_data(task, g_strdup(wp_folder), g_free);
    g_task_run_in_thread(task, thumbs_thread);
    g_object_unref(task);
}

// ---- folder watch: rescan when wallpapers are added/removed ----

static GFileMonitor *dir_monitor;
static guint rescan_id;

static void thumbs_scan(void);

static gboolean rescan_cb(gpointer data) {
    (void)data;
    rescan_id = 0;
    thumbs_scan();
    return G_SOURCE_REMOVE;
}

static void on_dir_changed(GFileMonitor *m, GFile *f, GFile *other,
                           GFileMonitorEvent ev, gpointer data) {
    (void)m;
    (void)f;
    (void)other;
    (void)data;
    if (ev == G_FILE_MONITOR_EVENT_CREATED ||
        ev == G_FILE_MONITOR_EVENT_DELETED ||
        ev == G_FILE_MONITOR_EVENT_MOVED_IN ||
        ev == G_FILE_MONITOR_EVENT_MOVED_OUT ||
        ev == G_FILE_MONITOR_EVENT_RENAMED ||
        ev == G_FILE_MONITOR_EVENT_CHANGES_DONE_HINT) {
        // debounce: a download fires many events before the file settles
        if (rescan_id)
            g_source_remove(rescan_id);
        rescan_id = g_timeout_add(600, rescan_cb, NULL);
    }
}

static void dir_monitor_start(void) {
    g_clear_object(&dir_monitor);
    GFile *f = g_file_new_for_path(wp_folder);
    dir_monitor = g_file_monitor_directory(f, G_FILE_MONITOR_WATCH_MOVES,
                                           NULL, NULL);
    g_object_unref(f);
    if (dir_monitor)
        g_signal_connect(dir_monitor, "changed",
                         G_CALLBACK(on_dir_changed), NULL);
}

// ---- folder picker ----

static void folder_chosen(GObject *src, GAsyncResult *res, gpointer data) {
    (void)data;
    GFile *f = gtk_file_dialog_select_folder_finish(GTK_FILE_DIALOG(src),
                                                    res, NULL);
    if (!f)
        return;
    g_free(wp_folder);
    wp_folder = g_file_get_path(f);
    g_object_unref(f);
    gtk_label_set_text(GTK_LABEL(folder_label), wp_folder);
    wp_state_save();
    dir_monitor_start(); // watch the new folder instead
    thumbs_scan();
}

static void on_folder_btn(GtkWidget *btn, gpointer data) {
    (void)btn;
    (void)data;
    GtkFileDialog *dlg = gtk_file_dialog_new();
    gtk_file_dialog_set_title(dlg, "Wallpaper folder");
    GFile *cur = g_file_new_for_path(wp_folder);
    gtk_file_dialog_set_initial_folder(dlg, cur);
    g_object_unref(cur);
    GtkRoot *root = gtk_widget_get_root(page_root);
    gtk_file_dialog_select_folder(dlg, GTK_WINDOW(root), NULL,
                                  folder_chosen, NULL);
    g_object_unref(dlg);
}

// ---- page ----

GtkWidget *wallpaper_page_new(void) {
    wp_state_load();
    monitors_load();

    GtkWidget *root = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    page_root = root;

    GtkWidget *header = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 10);
    gtk_widget_add_css_class(header, "pane-header");
    GtkWidget *title = gtk_label_new("Wallpaper");
    gtk_widget_add_css_class(title, "pane-title");
    gtk_box_append(GTK_BOX(header), title);
    status_label = gtk_label_new("");
    gtk_widget_add_css_class(status_label, "hint-label");
    gtk_widget_set_hexpand(status_label, TRUE);
    gtk_label_set_xalign(GTK_LABEL(status_label), 1.0);
    gtk_box_append(GTK_BOX(header), status_label);
    gtk_box_append(GTK_BOX(root), header);

    GtkWidget *body = gtk_box_new(GTK_ORIENTATION_VERTICAL, 14);
    gtk_widget_set_margin_start(body, 18);
    gtk_widget_set_margin_end(body, 18);
    gtk_widget_set_margin_top(body, 12);
    gtk_widget_set_margin_bottom(body, 18);

    // scope chips
    chips_box = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 10);
    rebuild_chips();
    gtk_box_append(GTK_BOX(body), chips_box);

    // folder row
    GtkWidget *frow = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 10);
    gtk_widget_add_css_class(frow, "nk-card");
    folder_label = gtk_label_new(wp_folder);
    gtk_widget_set_margin_start(folder_label, 8);
    gtk_label_set_ellipsize(GTK_LABEL(folder_label),
                            PANGO_ELLIPSIZE_START);
    gtk_label_set_xalign(GTK_LABEL(folder_label), 0.0);
    gtk_widget_set_hexpand(folder_label, TRUE);
    gtk_box_append(GTK_BOX(frow), folder_label);
    GtkWidget *change = gtk_button_new_with_label("Change folder…");
    gtk_widget_add_css_class(change, "advanced-btn");
    g_signal_connect(change, "clicked", G_CALLBACK(on_folder_btn), NULL);
    gtk_box_append(GTK_BOX(frow), change);
    gtk_box_append(GTK_BOX(body), frow);

    // thumbnail grid
    GtkWidget *scroll = gtk_scrolled_window_new();
    gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(scroll),
                                   GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
    gtk_widget_set_vexpand(scroll, TRUE);
    thumb_flow = gtk_flow_box_new();
    gtk_flow_box_set_selection_mode(GTK_FLOW_BOX(thumb_flow),
                                    GTK_SELECTION_NONE);
    gtk_flow_box_set_homogeneous(GTK_FLOW_BOX(thumb_flow), TRUE);
    gtk_flow_box_set_column_spacing(GTK_FLOW_BOX(thumb_flow), 4);
    gtk_flow_box_set_row_spacing(GTK_FLOW_BOX(thumb_flow), 4);
    gtk_flow_box_set_min_children_per_line(GTK_FLOW_BOX(thumb_flow), 2);
    gtk_flow_box_set_max_children_per_line(GTK_FLOW_BOX(thumb_flow), 6);
    gtk_widget_set_valign(thumb_flow, GTK_ALIGN_START);
    gtk_scrolled_window_set_child(GTK_SCROLLED_WINDOW(scroll), thumb_flow);
    gtk_box_append(GTK_BOX(body), scroll);

    gtk_box_append(GTK_BOX(root), body);

    dir_monitor_start();
    thumbs_scan();
    return root;
}
